version: '3.5'
services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - 80:80
      - 443:443
    networks:
      - nodeapp_daohuytuan
      - daiphamblog
      - node_daohuytuan
networks:
  nodeapp_daohuytuan:
   external:
     name: nodeapp_daohuytuan
  node_daohuytuan:
    external:
     name: node_daohuytuan
  daiphamblog:
   external:
    name: daiphamblog